; coords.asm generated by calc_coords.py

	fdb 8192, 2143
	fdb 8192, 1661
form_coords
	fdb 8192, 1216
	fdb 8192, 770
	fdb 8192, 288
	fdb 8192, -280
	fdb 6912, -384
	fdb 5850, -384
	fdb 5037, -384
	fdb 4348, -384
	fdb 3712, -384
	fdb 3075, -384
	fdb 2386, -384
	fdb 1573, -384
	fdb 512, -384
	fdb -768, -280
	fdb -768, 288
	fdb -768, 770
	fdb -768, 1215
	fdb -768, 1661
	fdb -768, 2143
	fdb -768, 2712
	fdb 511, 2816
	fdb 1573, 2816
	fdb 2386, 2816
	fdb 3075, 2816
	fdb 3711, 2816
	fdb 4348, 2816
	fdb 5037, 2816
	fdb 5850, 2816
	fdb 6911, 2816
	fdb 8192, 2712
	fdb 8192, 2143
	fdb 8192, 1661
	fdb 8192, 1216
	fdb 8192, 770


boss_coords
	fdb 8192, 1024
	fdb 8192, 16
	fdb 6912, -768
	fdb 4812, -768
	fdb 3328, -768
	fdb 1843, -768
	fdb -255, -768
	fdb -1536, 16
	fdb -1536, 1023
	fdb -1536, 2031
	fdb -256, 2816
	fdb 1843, 2816
	fdb 3327, 2816
	fdb 4812, 2816
	fdb 6911, 2816
	fdb 8192, 2031

; end coords.asm
