; coords.asm generated by calc_coords.py

	fdb 8128, 2130
	fdb 8128, 1655
form_coords
	fdb 8128, 1216
	fdb 8128, 776
	fdb 8128, 301
	fdb 8128, -259
	fdb 6848, -352
	fdb 5807, -352
	fdb 5010, -352
	fdb 4335, -352
	fdb 3712, -352
	fdb 3088, -352
	fdb 2413, -352
	fdb 1616, -352
	fdb 576, -352
	fdb -704, -259
	fdb -704, 301
	fdb -704, 776
	fdb -704, 1215
	fdb -704, 1655
	fdb -704, 2130
	fdb -704, 2691
	fdb 575, 2784
	fdb 1616, 2784
	fdb 2413, 2784
	fdb 3088, 2784
	fdb 3711, 2784
	fdb 4335, 2784
	fdb 5010, 2784
	fdb 5807, 2784
	fdb 6847, 2784
	fdb 8128, 2691
	fdb 8128, 2130
	fdb 8128, 1655
	fdb 8128, 1216
	fdb 8128, 776


boss_coords
	fdb 8128, 1024
	fdb 8128, 29
	fdb 6848, -736
	fdb 4786, -736
	fdb 3328, -736
	fdb 1869, -736
	fdb -191, -736
	fdb -1472, 29
	fdb -1472, 1023
	fdb -1472, 2018
	fdb -192, 2784
	fdb 1869, 2784
	fdb 3327, 2784
	fdb 4786, 2784
	fdb 6847, 2784
	fdb 8128, 2018

; end coords.asm
