; Generated by motorpng/motorpng.py
; 2018/10/12 21:36:09
; Source image sp_1000.png (36x12)
; Output size 12x12
; Output bit depth 2

	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $CC,$00,$00
	FCB $CC,$C3,$0C
	FCB $CC,$C3,$0C
	FCB $CC,$C3,$0C
	FCB $CC,$00,$00
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF

	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $21,$5F,$EA
	FCB $21,$1C,$E2
	FCB $21,$1C,$E2
	FCB $21,$1C,$E2
	FCB $21,$5F,$EA
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00

	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $CC,$00,$00
	FCB $CC,$C3,$0C
	FCB $CC,$C3,$0C
	FCB $CC,$C3,$0C
	FCB $CC,$00,$00
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF

	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $32,$A5,$7F
	FCB $32,$24,$73
	FCB $32,$24,$73
	FCB $32,$24,$73
	FCB $32,$A5,$7F
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00

	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $CC,$00,$00
	FCB $CC,$C3,$0C
	FCB $CC,$C3,$0C
	FCB $CC,$C3,$0C
	FCB $CC,$00,$00
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF

	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $13,$FA,$95
	FCB $13,$38,$91
	FCB $13,$38,$91
	FCB $13,$38,$91
	FCB $13,$FA,$95
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00

