; Generated by ./test.py
; 2018/07/29 21:48:47
; Source image: sp_flap_2.png (36x12)
; Output size: 12x12
; Output bit depth: 2

	fcb $f3,$fc,$03
	fcb $fc,$f0,$00
	fcb $3f,$30,$00
	fcb $cf,$c0,$00
	fcb $f3,$00,$00
	fcb $fc,$00,$03
	fcb $c0,$00,$3f
	fcb $00,$00,$cf
	fcb $00,$03,$f3
	fcb $00,$0c,$fc
	fcb $00,$0f,$3f
	fcb $c0,$3f,$cf

	fcb $0c,$01,$54
	fcb $01,$05,$fe
	fcb $c0,$45,$be
	fcb $30,$30,$2e
	fcb $0c,$4c,$2a
	fcb $01,$03,$a8
	fcb $14,$42,$c0
	fcb $54,$3a,$10
	fcb $78,$2c,$04
	fcb $7e,$a1,$02
	fcb $7f,$a0,$40
	fcb $2a,$80,$10

	fcb $f3,$fc,$03
	fcb $fc,$f0,$00
	fcb $3f,$30,$00
	fcb $cf,$c0,$00
	fcb $f3,$00,$00
	fcb $fc,$00,$03
	fcb $c0,$00,$3f
	fcb $00,$00,$cf
	fcb $00,$03,$f3
	fcb $00,$0c,$fc
	fcb $00,$0f,$3f
	fcb $c0,$3f,$cf

	fcb $04,$01,$54
	fcb $01,$05,$fe
	fcb $40,$45,$be
	fcb $10,$30,$2e
	fcb $04,$4c,$2a
	fcb $03,$01,$a8
	fcb $14,$c2,$40
	fcb $54,$1a,$20
	fcb $78,$24,$08
	fcb $7e,$a2,$02
	fcb $7f,$a0,$80
	fcb $2a,$80,$20

	fcb $f3,$fc,$03
	fcb $fc,$f0,$00
	fcb $3f,$30,$00
	fcb $cf,$c0,$00
	fcb $f3,$00,$00
	fcb $fc,$00,$03
	fcb $c0,$00,$3f
	fcb $00,$00,$cf
	fcb $00,$03,$f3
	fcb $00,$0c,$fc
	fcb $00,$0f,$3f
	fcb $c0,$3f,$cf

	fcb $0c,$01,$54
	fcb $03,$05,$fe
	fcb $c0,$c5,$be
	fcb $10,$10,$2e
	fcb $04,$44,$2a
	fcb $03,$03,$a8
	fcb $14,$c2,$c0
	fcb $54,$3a,$10
	fcb $78,$2c,$04
	fcb $7e,$a1,$01
	fcb $7f,$a0,$40
	fcb $2a,$80,$20

