; Generated by motorpng/motorpng.py
; 2018/08/09 21:15:51
; Source image sp_fireball.png (24x12)
; Output size 12x12
; Output bit depth 2

	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$C3,$FF
	FCB $FC,$00,$3F
	FCB $FC,$00,$3F
	FCB $F0,$00,$0F
	FCB $F0,$00,$0F
	FCB $FC,$00,$3F
	FCB $FC,$00,$3F
	FCB $FF,$C3,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF

	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$3C,$00
	FCB $03,$D7,$C0
	FCB $03,$55,$C0
	FCB $0D,$55,$70
	FCB $0D,$55,$70
	FCB $03,$55,$C0
	FCB $03,$D7,$C0
	FCB $00,$3C,$00
	FCB $00,$00,$00
	FCB $00,$00,$00

	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$C3,$FF
	FCB $FF,$00,$FF
	FCB $FC,$00,$3F
	FCB $FC,$00,$3F
	FCB $FF,$00,$FF
	FCB $FF,$C3,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF
	FCB $FF,$FF,$FF

	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$3C,$00
	FCB $00,$D7,$00
	FCB $03,$55,$C0
	FCB $03,$55,$C0
	FCB $00,$D7,$00
	FCB $00,$3C,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00

