; Generated by motorpng/motorpng.py
; 2018/10/15 22:04:44
; Source image sp_jet.png (12x12)
; Output size 12x12
; Output bit depth 2

	FCB $FF,$C3,$FF
	FCB $FF,$C3,$FF
	FCB $FF,$C3,$FF
	FCB $FF,$00,$FF
	FCB $FF,$00,$FF
	FCB $FF,$00,$FF
	FCB $3C,$00,$3C
	FCB $30,$00,$0C
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $30,$3C,$0C

	FCB $00,$1C,$00
	FCB $00,$1C,$00
	FCB $00,$1C,$00
	FCB $00,$7E,$00
	FCB $00,$7E,$00
	FCB $00,$56,$00
	FCB $41,$42,$83
	FCB $45,$42,$A3
	FCB $54,$EB,$2B
	FCB $51,$3C,$4B
	FCB $71,$FF,$4F
	FCB $4D,$C3,$73

