; Generated by motorpng/motorpng.py
; 2018/08/12 20:18:49
; Source image sp_rot.png (36x12)
; Output size 12x12
; Output bit depth 2

	FCB $FF,$00,$FF
	FCB $F0,$00,$0F
	FCB $C0,$00,$03
	FCB $C0,$00,$03
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $C0,$00,$03
	FCB $C0,$00,$03
	FCB $F0,$00,$0F
	FCB $FF,$00,$FF

	FCB $00,$55,$00
	FCB $05,$FF,$50
	FCB $1F,$FC,$38
	FCB $1F,$D4,$38
	FCB $43,$7E,$FE
	FCB $41,$FF,$BE
	FCB $7D,$FF,$BE
	FCB $7F,$BE,$FE
	FCB $1F,$EB,$F8
	FCB $1F,$F0,$F8
	FCB $0A,$F0,$A0
	FCB $00,$AA,$00

	FCB $FF,$00,$FF
	FCB $F0,$00,$0F
	FCB $C0,$00,$03
	FCB $C0,$00,$03
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $C0,$00,$03
	FCB $C0,$00,$03
	FCB $F0,$00,$0F
	FCB $FF,$00,$FF

	FCB $00,$55,$00
	FCB $05,$FF,$50
	FCB $1C,$3F,$F8
	FCB $1C,$17,$F8
	FCB $7F,$7E,$FE
	FCB $7D,$FF,$82
	FCB $7D,$FF,$82
	FCB $7F,$BE,$FE
	FCB $1F,$EB,$F8
	FCB $1F,$0F,$F8
	FCB $0A,$0F,$A0
	FCB $00,$AA,$00

	FCB $FF,$00,$FF
	FCB $F0,$00,$0F
	FCB $C0,$00,$03
	FCB $C0,$00,$03
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $00,$00,$00
	FCB $C0,$00,$03
	FCB $C0,$00,$03
	FCB $F0,$00,$0F
	FCB $FF,$00,$FF

	FCB $00,$55,$00
	FCB $05,$C3,$50
	FCB $1F,$C3,$F8
	FCB $1F,$D7,$F8
	FCB $7F,$7E,$FE
	FCB $7D,$FF,$BE
	FCB $7D,$FF,$BE
	FCB $70,$BE,$0E
	FCB $10,$EB,$08
	FCB $1F,$FF,$F8
	FCB $0A,$FF,$A0
	FCB $00,$AA,$00

