; Generated by ./test.py
; 2018/07/20 23:14:21
; Source image: sp_std2.png (12x12)
; Output size: 12x12
; Output bit depth: 2

sp_std2
	fcb $ff,$00,$ff
	fcb $f0,$00,$0f
	fcb $c0,$00,$03
	fcb $c0,$00,$03
	fcb $00,$00,$00
	fcb $00,$00,$00
	fcb $00,$00,$00
	fcb $00,$00,$00
	fcb $c0,$00,$03
	fcb $c0,$00,$03
	fcb $f0,$00,$0f
	fcb $ff,$00,$ff

	fcb $00,$55,$00
	fcb $05,$00,$50
	fcb $10,$3c,$08
	fcb $10,$55,$08
	fcb $41,$00,$82
	fcb $4d,$00,$a2
	fcb $4d,$00,$a2
	fcb $41,$00,$82
	fcb $10,$aa,$88
	fcb $10,$28,$08
	fcb $0a,$00,$a0
	fcb $00,$aa,$00

